apiVersion: v2
name: actual
description: "Actual Budget deployment for homelab"
type: application
version: 0.1.0
dependencies:
  - name: home-ops-app-chart
    version: 0.3.1
    repository: oci://zot.schober.dev/charts
