apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: versitygw-client-secret
  namespace: {{ .Release.Namespace }}
spec:
  length: 42
  noUpper: false
  allowRepeat: true
---
{{- range .Values.cnpgClients }}
{{- $app := . }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $app }}-versitygw-generated
  namespace: {{ $.Release.Namespace }}
spec:
  refreshPolicy: CreatedOnce
  target:
    name: {{ $app }}-versitygw-generated
    template:
      engineVersion: v2
      data:
        accessKeyId: "{{ $app }}-backup"
        secretAccessKey: "{{ `{{ .password }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: versitygw-client-secret
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $app }}-versitygw-push
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  deletionPolicy: None
  updatePolicy: Replace
  secretStoreRefs:
    - name: bitwarden-cnpg-secrets
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $app }}-versitygw-generated
  data:
    - match:
        secretKey: accessKeyId
        remoteRef:
          remoteKey: {{ $app }}-backup-id
    - match:
        secretKey: secretAccessKey
        remoteRef:
          remoteKey: {{ $app }}-backup-secret
---
{{- end }}
