apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flux-zot-oci-credentials
  namespace: flux-system
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  target:
    name: flux-zot-oci-credentials
    template:
      type: Opaque
  data:
    - secretKey: username
      remoteRef:
        key: argocd-zot-repo-username
    - secretKey: password
      remoteRef:
        key: argocd-zot-repo-password
