{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: forgejo-runner
    release: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: forgejo-runner-secret
    template:
      type: Opaque
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.externalSecret.keys.token }}
{{- end }}
