apiVersion: v2
name: qui
description: "qui - qBittorrent WebUI with Authentik OIDC"
type: application
version: 0.1.0
dependencies:
  - name: home-ops-app-chart
    version: 0.3.1
    repository: oci://zot.schober.dev/charts
  - name: home-ops-cnpg-cluster-chart
    version: 0.1.0
    repository: oci://zot.schober.dev/charts
    condition: home-ops-cnpg-cluster-chart.enabled
