serviceAccount:
  create: true
  name: "forgejo-runner"
  annotations: {}

externalSecret:
  enabled: true
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-app-secrets
    kind: ClusterSecretStore
  keys:
    token: forgejo-actions-secret