apiVersion: v1
kind: Service
metadata:
  name: netbird-server-h2c
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: netbird
    app.kubernetes.io/name: netbird
  ports:
    - name: grpc-h2c
      port: 80
      targetPort: http
      protocol: TCP
      appProtocol: kubernetes.io/h2c
