apiVersion: v1
kind: Service
metadata:
  name: netbird-stun
  namespace: {{ .Release.Namespace }}
  annotations:
    io.cilium/lb-ipam-ips: 10.1.40.90
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: netbird
    app.kubernetes.io/name: netbird
  ports:
    - name: stun-udp
      port: 3478
      targetPort: stun-udp
      protocol: UDP
